### ISSUE TITLE
[Bug] SignGUI does not support the server version "1_21_R2"

### ISSUE THREAD

**Issue by gamenTV** [Rapha149/SignGUI#22]
### API version

2.4.1

### Server software and version

Spigot 1.21.3-R0.1-SNAPSHOT

### Steps to reproduce

```bash
open a sign GUI
```

### Expected behaviour

the sign should open as expected

### What is actually happening?

Caused by: java.lang.IllegalStateException: SignGUI does not support the server version "1_21_R2"
	at de.rapha149.signgui.SignGUI.<clinit>(SignGUI.java:101) ~[?:?]
	at nevojobs.nevojobs.jobs.system.JobEditGUI.changeJobEdit(JobEditGUI.java:152) ~[?:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	... 20 more

**Comment by Rapha149** [comment]
I'm aware of this but I didn't get around to updating the API yet.

**Comment by Capwave** [comment]
When can we expect this approximately?

**Comment by Rapha149** [comment]
In the next few days probably

**Comment by Rapha149** [comment]
Just released the update, sorry for the delay!
It probably will take a few hours for it to get published on Maven Central.
